Repository LINE-NOW/LINENOW-Web, pull requests merged in 2024-09, with the labels that each got.

#2 [Feature] #1 - Setting Initial Project
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/assets/fonts/PretendardVariable.woff2
  src/components/button/Button.styled.ts
  src/components/button/Button.tsx
  src/components/layout/Layout.tsx
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/myWaitingList/MyWaitingListPage.tsx
  src/pages/setting/SettingPage.tsx
  src/pages/waitingCheck/WaitingCheckPage.tsx
  src/pages/waitingDetail/WaitingDetailPage.tsx
  src/routes/router.tsx
  src/styles/global.ts
  src/styles/theme.ts
  src/test/FontTest.tsx
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature, 🍀 서현작업

#5 [Feature] #3 - Create Modal, Bottomsheet Component
  package-lock.json
  package.json
  src/App.tsx
  src/atoms/bottomsheet.ts
  src/atoms/modal.ts
  src/components/bottomsheet/Bottomsheet.styled.ts
  src/components/bottomsheet/Bottomsheet.tsx
  src/components/button/Button.styled.ts
  src/components/button/Button.tsx
  src/components/button/ButtonLayout.tsx
  src/components/layout/PageLayout.tsx
  src/components/modal/Modal.styled.ts
  src/components/modal/Modal.tsx
  src/hooks/useBottomsheet.ts
  src/hooks/useModal.ts
  src/pages/main/MainPage.tsx
  src/routes/router.tsx
  src/styles/global.ts
  src/styles/theme.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature, 🍀 서현작업

#6 [Feature] #4 - Create Main Page
  package.json
  public/icons/icon_check_ blue.svg
  public/icons/icon_check_gray_light.svg
  public/icons/icon_close_gray.svg
  public/icons/icon_down_gray.svg
  public/icons/icon_down_gray_light.svg
  public/icons/icon_drop_gray.svg
  public/icons/icon_edit_gray.svg
  public/icons/icon_kakao_kakao.svg
  public/icons/icon_left_gray.svg
  public/icons/icon_location_gray.svg
  public/icons/icon_location_gray_light.svg
  public/icons/icon_right_gray.svg
  public/icons/icon_right_white.svg
  public/icons/icon_setting_white.svg
  public/icons/icon_sort_gray.svg
  src/components/boothCard/BoothCard.styled.ts
  src/components/boothCard/BoothCard.tsx
  src/components/bottomsheet/Bottomsheet.styled.ts
  src/components/button/Button.styled.ts
  src/components/button/Button.tsx
  src/components/button/CustomButton.styled.ts
  src/components/button/CustomButton.tsx
  src/components/chip/Chip.styled.ts
  src/components/chip/Chip.tsx
  src/components/label/IconLabel.tsx
  src/components/label/IconLable.styled.ts
  src/components/modal/Modal.styled.ts
  src/components/modal/Modal.tsx
  src/components/waitingCard/WaitingCard.styled.ts
  src/components/waitingCard/WaitingCard.tsx
  src/constants/style.ts
  src/layouts/DefaultPageLayout.tsx
  src/pages/main/MainPage.styled.ts
  src/pages/main/MainPage.tsx
  src/pages/main/_components/boothList/MainBoothList.styled.ts
  src/pages/main/_components/boothList/MainBoothList.tsx
  src/pages/main/_components/boothList/MinaBoothListHeader.tsx
  src/pages/main/_components/navigation/MainNavigation.styled.ts
  src/pages/main/_components/navigation/MainNavigation.tsx
  src/pages/main/_hooks/useMainNavigation.ts
  src/routes/router.tsx
  src/styles/animation.ts
  src/styles/global.ts
  src/styles/theme.ts
  src/types/style.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature, 🍀 서현작업

#10 [Feature] #9 - Create Setting Page
  src/pages/setting/SettingPage.styled.ts
  src/pages/setting/SettingPage.tsx
  src/pages/setting/_components/deleteID/SettingDeleteID.styled.ts
  src/pages/setting/_components/deleteID/SettingDeleteID.tsx
  src/pages/setting/_components/settingItem/SettingItem.styled.ts
  src/pages/setting/_components/settingItem/SettingItem.tsx
Labels: ✨ Feature, 🍀 유진작업

#15 [Feature] #13 - Create Waiting Detail Page
  public/images/image_caution.png
  src/components/boothCard/BoothCard.styled.ts
  src/components/boothCard/BoothCard.tsx
  src/components/bottomButton/BottomButton.styled.ts
  src/components/bottomButton/BottomButton.tsx
  src/components/navigation/Navigation.tsx
  src/components/separator/Separator.tsx
  src/pages/main/_components/boothList/MainBoothList.tsx
  src/pages/waitingDetail/WaitingDetailPage.styled.ts
  src/pages/waitingDetail/WaitingDetailPage.tsx
  src/pages/waitingDetail/_components/WaitingDetailCaution.styled.tsx
  src/pages/waitingDetail/_components/WaitingDetailCaution.tsx
  src/pages/waitingDetail/_components/WaitingDetailCautionItem.tsx
Labels: ✨ Feature, 🍀 찬주작업

#16 [Chore] #13 waiting detail page - create waiting cancel modal
  src/components/bottomButton/BottomButton.styled.ts
  src/components/bottomButton/BottomButton.tsx
  src/pages/main/_components/boothList/MainBoothList.tsx
  src/pages/waitingDetail/WaitingDetailPage.styled.ts
  src/pages/waitingDetail/WaitingDetailPage.tsx
Labels: 🍀 찬주작업, ✏️ Chore

#19 [Feature] #12 - Create Booth Detail Page
  public/images/image_thumbnail_1.png
  src/constants/booth.ts
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/boothDetail/_components/card/BoothDeatilCard.styled.ts
  src/pages/boothDetail/_components/card/BoothDetailCard.tsx
  src/pages/boothDetail/_components/common/style.ts
  src/pages/boothDetail/_components/content/BoothDetailContent.styled.ts
  src/pages/boothDetail/_components/content/BoothDetailContent.tsx
  src/pages/boothDetail/_components/index.ts
  src/pages/boothDetail/_components/menu/BoothDetailMenu.styled.ts
  src/pages/boothDetail/_components/menu/BoothDetailMenu.tsx
  src/pages/boothDetail/_components/notice/BoothDetailNotice.styled.ts
  src/pages/boothDetail/_components/notice/BoothDetailNotice.tsx
  src/pages/boothDetail/_hooks/useBoothID.ts
Labels: ✨ Feature, 🍀 세호작업

#20 [Feature] #18 Create Waiting Check Page
  public/icons/icon_checkBox_after.svg
  public/icons/icon_checkBox_before.svg
  src/components/boothCard/BoothCard.styled.ts
  src/components/boothCard/BoothCard.tsx
  src/components/infobottomButton/InfoBottomButton.styled.ts
  src/components/infobottomButton/InfoBottomButton.tsx
  src/components/waitingCard/WaitingCard.styled.ts
  src/components/waitingCard/WaitingCard.tsx
  src/constants/waitingCaution.ts
  src/pages/main/_components/navigation/MainNavigation.tsx
  src/pages/waitingCheck/WaitingCheckPage.styled.ts
  src/pages/waitingCheck/WaitingCheckPage.tsx
  src/pages/waitingCheck/_components/WaitingCheckCautionModal.tsx
  src/pages/waitingCheck/_components/WaitingCheckModal.tsx
  src/pages/waitingCheck/_components/WaitingCheckPeople.styled.ts
  src/pages/waitingCheck/_components/WaitingCheckPeople.tsx
  src/pages/waitingCheck/_hooks/useWaitingId.ts
  src/pages/waitingDetail/_components/WaitingDetailCaution.styled.tsx
  src/pages/waitingDetail/_components/WaitingDetailCaution.tsx
  src/styles/global.ts
Labels: ✨ Feature, 🍀 찬주작업

#24 [Feature] #22 - Setting Initial Mock API
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/apis/domains/waiting/_interfaces.ts
  src/apis/domains/waiting/apis.ts
  src/apis/domains/waiting/queries.ts
  src/apis/dummy/dummyWaitingsResponse.ts
  src/apis/instance.ts
  src/components/button/CustomButton.styled.ts
  src/components/chip/Chip.styled.ts
  src/components/spinner/Spinner.styled.ts
  src/components/spinner/Spinner.tsx
  src/components/waitingCard/WaitingCard.tsx
  src/components/waitingCard/_hooks/useWaitingCard.tsx
  src/components/waitingCard/interfaces/waitingCard.ts
  src/hooks/apis/waiting.ts
  src/layouts/DefaultPageLayout.tsx
  src/lib/interfaces/booth.ts
  src/lib/interfaces/waiting.ts
  src/lib/types/status.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/dummy/waitings.ts
  src/mocks/handlers.ts
  src/pages/main/_components/navigation/MainNavigation.tsx
  src/pages/myWaitingList/MyWaitingListPage.tsx
Labels: 🛜 API, 🍀 서현작업

#25 [Feature] #17 - Create Login Bottom Sheet
  src/components/bottomsheet/Bottomsheet.tsx
  src/components/login/LoginBottomsheetContent.styled.ts
  src/components/login/LoginBottomsheetContent.tsx
  src/pages/setting/SettingPage.tsx
Labels: ✨ Feature, 🍀 유진작업

#27 [Fix] #23 - Modify BoothDetails page slider
  public/images/image_thumbnail_2.png
  src/apis/dummy/dummyBoothDetailResponse.ts
  src/lib/interfaces/boothDeatil.ts
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/boothDetail/_components/card/BoothDetailCard.tsx
Labels: 🛠️ Fix, 🍀 세호작업
