Repository LINE-NOW/LINENOW-Web, pull requests merged in 2024-10, with the labels that each got.

#30 [Feature] #29 - Update Booth Card and Setting BoothList Mock API
  package-lock.json
  package.json
  public/images/image_waitingDetailCaution1.png
  public/images/image_waitingDetailCaution2.png
  src/apis/domains/boothList/_interfaces.ts
  src/apis/domains/boothList/apis.ts
  src/apis/domains/boothList/queries.ts
  src/components/boothCard/BoothCard.styled.ts
  src/components/boothCard/boothCardDetail.tsx
  src/components/boothCard/boothCardLayout.tsx
  src/components/boothCard/boothCardMain.tsx
  src/hooks/apis/boothList.ts
  src/mocks/dummy/boothList.ts
  src/mocks/handlers.ts
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/main/_components/boothList/MainBoothList.tsx
  src/pages/waitingCheck/WaitingCheckPage.tsx
  src/pages/waitingCheck/_components/WaitingCheckModal.tsx
  src/pages/waitingDetail/WaitingDetailPage.tsx
  src/pages/waitingDetail/_components/WaitingDetailCaution.styled.tsx
  src/pages/waitingDetail/_components/WaitingDetailCaution.tsx
Labels: 🛜 API, 🍀 찬주작업

#32 [Fix] #31 - Fixing build errors
  .gitignore
  src/components/button/CustomButton.tsx
  src/pages/boothDetail/BoothDetailPage.tsx
Labels: 🛠️ Fix, 🍀 서현작업

#34 [Feature] #33 - Creating Service Footer
  public/images/image_vertical_logo.svg
  src/pages/setting/SettingPage.styled.ts
  src/pages/setting/SettingPage.tsx
Labels: ✨ Feature, 🍀 서현작업

#36 [Feature] #35 - Creating Signup Page
  .gitignore
  src/App.tsx
  src/apis/domains/waiting/apis.ts
  src/apis/instance.ts
  src/atoms/auth.ts
  src/components/bottomsheet/Bottomsheet.tsx
  src/components/login/LoginBottomsheetContent.tsx
  src/components/waitingCard/WaitingCard.styled.ts
  src/components/waitingCard/WaitingCardLogin.tsx
  src/hooks/useAuth.ts
  src/main.tsx
  src/pages/main/_components/navigation/MainNavigation.tsx
  src/pages/signup/SignupPage.tsx
  src/routes/router.tsx
Labels: 🍀 서현작업, ✏️ Chore

#38 [Feature] Setting Booth API
  package-lock.json
  package.json
  src/apis/domains/booth/_interfaces.ts
  src/apis/domains/booth/apis.ts
  src/apis/domains/booth/queries.ts
  src/apis/domains/waiting/_interfaces.ts
  src/apis/domains/waiting/apis.ts
  src/apis/instance.ts
  src/components/waitingCard/WaitingCard.tsx
  src/components/waitingCard/WaitingCardLogin.tsx
  src/components/waitingCard/interfaces/waitingCard.ts
  src/hooks/apis/booth.ts
  src/lib/interfaces/waiting.ts
  src/mocks/dummy/booth.ts
  src/mocks/handlers.ts
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/boothDetail/_components/card/BoothDeatilCard.styled.ts
  src/pages/boothDetail/_components/card/BoothDetailCard.tsx
  src/pages/boothDetail/_components/content/BoothDetailContent.tsx
  src/pages/boothDetail/_components/menu/BoothDetailMenu.tsx
  src/pages/boothDetail/_components/notice/BoothDetailNotice.tsx
  src/pages/waitingCheck/WaitingCheckPage.tsx
  src/pages/waitingCheck/_components/WaitingCheckCautionModal.tsx
  src/pages/waitingCheck/_components/WaitingCheckModal.tsx
  src/routes/router.tsx
Labels: 🛜 API, 🍀 찬주작업

#41 [Feature] #39 - Setting Auth API
  src/apis/domains/auth/deleteID/apis.ts
  src/apis/domains/auth/logout/apis.ts
  src/apis/instance.ts
  src/mocks/handlers.ts
  src/pages/setting/SettingPage.tsx
  src/pages/setting/_components/deleteID/SettingDeleteID.tsx
Labels: 🛜 API, 🍀 유진작업

#43 [Feature] #42 - Create A Feature Of Items - Setting Page
  src/apis/domains/auth/logout/apis.ts
  src/apis/instance.ts
  src/main.tsx
  src/pages/setting/SettingPage.tsx
Labels: ✨ Feature, 🍀 유진작업

#40 [Feature] #28 - Implement an Entry UI
  public/images/image_boothCardThumbnail.png
  src/apis/domains/entry/_interface.ts
  src/apis/domains/entry/api.ts
  src/apis/instance.ts
  src/atoms/entrance.ts
  src/components/entrance/Entrance.styled.ts
  src/components/entrance/Entrance.tsx
  src/components/modal/Modal.tsx
  src/hooks/apis/entry.ts
  src/hooks/useCheckWaitingStatus.tsx
  src/hooks/useEntrance.ts
  src/hooks/useTimer.ts
  src/lib/interfaces/waiting.ts
  src/pages/main/MainPage.tsx
Labels: ✨ Feature, 🍀 세호작업

#46 [Feature] #45 - Language Settings - Managing Status with Jotai
  src/atoms/language.ts
  src/pages/setting/SettingPage.tsx
Labels: ✨ Feature, 🍀 유진작업

#50 [Feature] #35 - Setting Auth
  src/App.tsx
  src/apis/instance.ts
  src/atoms/auth.ts
  src/hooks/apis/waiting.ts
  src/hooks/useAuth.ts
  src/main.tsx
  src/mocks/_components/TestTool.tsx
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/_components/boothList/MainBoothList.tsx
  src/pages/main/_components/boothList/MainBoothListHeader.tsx
  src/pages/main/_components/boothList/MinaBoothListHeader.tsx
  src/pages/main/_components/navigation/MainNavigation.tsx
  src/pages/main/_hooks/useMainNavigation.ts
  src/pages/myWaitingList/MyWaitingListPage.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/router.tsx
Labels: ✨ Feature, 🍀 서현작업

#49 [Refactor] #47 - Entry logic refactoring
  src/components/entrance/Entrance.tsx
  src/components/entrance/entranceUtils.ts
  src/hooks/useCheckWaitingStatus.tsx
Labels: ✏️ Chore, 🍀 세호작업

#52 [Feature] #37 - Setting Waiting Detail API
  src/apis/domains/waiting/_interfaces.ts
  src/apis/domains/waiting/apis.ts
  src/apis/domains/waitingDetail/_interfaces.ts
  src/apis/domains/waitingDetail/apis.ts
  src/apis/domains/waitingDetail/queries.ts
  src/apis/instance.ts
  src/components/boothCard/boothCardDetail.tsx
  src/components/entrance/Entrance.tsx
  src/components/waitingCard/WaitingCard.tsx
  src/hooks/apis/waitingDetail.ts
  src/lib/interfaces/waitingCheck.ts
  src/lib/interfaces/waitingDetail.ts
  src/mocks/dummy/waitingDetail.ts
  src/mocks/handlers.ts
  src/pages/waitingCheck/WaitingCheckPage.tsx
  src/pages/waitingCheck/_components/WaitingCheckCautionModal.tsx
  src/pages/waitingDetail/WaitingDetailPage.tsx
Labels: ✨ Feature, 🍀 찬주작업

#54 [Feature]-#51 Update Booth Detail & Waiting flow
  src/apis/domains/waitingCancel/apis.ts
  src/apis/domains/waitingDetail/_interfaces.ts
  src/components/boothCard/boothCardDetail.tsx
  src/components/button/Button.styled.ts
  src/components/entrance/Entrance.tsx
  src/lib/interfaces/waitingDetail.ts
  src/mocks/dummy/booth.ts
  src/mocks/dummy/waitingDetail.ts
  src/mocks/handlers.ts
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/waitingDetail/WaitingDetailPage.tsx
Labels: 🛜 API, 🍀 찬주작업

#56 [Fix] #55 - Fixing Waiting Card
  src/apis/domains/waiting/_interfaces.ts
  src/components/button/Button.styled.ts
  src/components/waitingCard/WaitingCard.styled.ts
  src/components/waitingCard/WaitingCard.tsx
  src/components/waitingCard/WaitingCardLogin.tsx
  src/components/waitingCard/_hooks/useWaitingCard.tsx
  src/lib/interfaces/waiting.ts
  src/lib/types/status.ts
  src/mocks/dummy/waitingDetail.ts
  src/mocks/dummy/waitings.ts
  src/pages/setting/SettingPage.styled.ts
  src/pages/setting/SettingPage.tsx
Labels: 🛠️ Fix, 🍀 서현작업

#58 [Fix] #51 - Fix waiting cancel : waitingID props
  src/components/waitingCard/WaitingCard.tsx
  src/pages/waitingCheck/_components/WaitingCheckCautionModal.tsx
  src/pages/waitingDetail/WaitingDetailPage.tsx
Labels: 🛜 API, 🍀 찬주작업

#61 [Feature] #57 - Developing Siginup Page, Login Page
  src/components/button/Button.styled.ts
  src/components/button/Button.tsx
  src/components/inputText/InputText.styled.ts
  src/components/inputText/InputText.tsx
  src/components/navigation/Navigation.tsx
  src/hooks/useForm.ts
  src/lib/interfaces/form.ts
  src/pages/login/LoginPage.styled.ts
  src/pages/login/LoginPage.tsx
  src/pages/login/LoginValidateConfig.ts
  src/pages/signup/SignupPage.styled.ts
  src/pages/signup/SignupPage.tsx
  src/pages/signup/SignupValidateConfig.ts
  src/routes/GuestRoute.tsx
  src/routes/router.tsx
  src/styles/theme.ts
  src/utils/validateConfig.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature, 🍀 서현작업

#62 [Feauture] #59 - Block Back Btn
  src/apis/instance.ts
  src/components/waitingCard/WaitingCard.tsx
  src/mocks/handlers.ts
  src/pages/waitingCheck/_components/WaitingCheckCautionModal.tsx
  src/pages/waitingDetail/WaitingDetailPage.tsx
Labels: ✨ Feature, 🍀 찬주작업

#64 [Chore] #63 - Add No Waiting Card
  public/images/image_icon.png
  public/images/image_waitingNoCard.png
  src/components/waitingCard/WaitingCard.styled.ts
  src/components/waitingCard/WaitingCard.tsx
  src/components/waitingCard/WaitingCardLayout.tsx
  src/components/waitingCard/WaitingCardLogin.tsx
  src/components/waitingCard/WaitingCardNoCard.tsx
  src/pages/main/_components/navigation/MainNavigation.tsx
Labels: 🍀 찬주작업, ✏️ Chore

#68 [Fix] #66 - Fixing unused import
  src/components/waitingCard/WaitingCardLogin.tsx
  src/pages/main/MainPage.tsx
Labels: 🛠️ Fix, 🍀 서현작업

#69 [Feature] #60 - Connecting Auth API
  src/apis/domains/auth/deleteID/_interfaces.ts
  src/apis/domains/auth/deleteID/apis.ts
  src/apis/domains/auth/login/_interfaces.ts
  src/apis/domains/auth/login/apis.ts
  src/apis/domains/auth/logout/_interfaces.ts
  src/apis/domains/auth/logout/apis.ts
  src/apis/domains/auth/signup/_interfaces.ts
  src/apis/domains/auth/signup/apis.ts
  src/apis/instance.ts
  src/atoms/isLoading.ts
  src/components/login/LoginBottomsheetContent.styled.ts
  src/components/login/LoginBottomsheetContent.tsx
  src/hooks/apis/auth.ts
  src/hooks/useAuth.ts
  src/hooks/useIsLoading.ts
  src/main.tsx
  src/pages/login/LoginPage.tsx
  src/pages/setting/SettingPage.tsx
  src/pages/setting/_components/deleteID/SettingDeleteID.tsx
  src/pages/signup/SignupPage.tsx
Labels: 🛜 API, 🍀 유진작업

#71 [Chore] #65 - Implement booth open logic
  src/apis/domains/booth/_interfaces.ts
  src/components/entrance/Entrance.tsx
  src/pages/boothDetail/BoothDetailPage.tsx
Labels: ✏️ Chore, 🍀 세호작업

#72 [Refactor] #70 - Refactoring postWaitingCancel, postWaiting
  src/App.tsx
  src/apis/domains/waiting/apis.ts
  src/apis/domains/waitingDetail/apis.ts
  src/apis/instance.ts
  src/components/boothCard/BoothCard.styled.ts
  src/components/boothCard/boothCardDetail.tsx
  src/components/boothCard/boothCardLayout.tsx
  src/components/boothCard/boothCardMain.tsx
  src/components/bottomButton/BottomButton.styled.ts
  src/components/navigation/Navigation.styled.ts
  src/hooks/apis/auth.ts
  src/hooks/apis/waiting.ts
  src/hooks/apis/waitingDetail.ts
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/signup/SignupPage.tsx
  src/pages/signup/SignupValidateConfig.ts
  src/pages/signup/SignupVerification.txt
  src/pages/waitingCheck/_components/WaitingCheckCautionModal.tsx
  src/pages/waitingDetail/WaitingDetailPage.tsx
Labels: 🛠️ Fix, 🍀 서현작업

#75 [Fix] #73 - Fixing Booth Detail Bottom Button, Main Booth Card Chips
  src/App.tsx
  src/apis/domains/booth/_interfaces.ts
  src/apis/domains/boothList/_interfaces.ts
  src/apis/domains/entry/api.ts
  src/apis/instance.ts
  src/components/boothCard/boothCardDetail.tsx
  src/components/boothCard/boothCardMain.tsx
  src/components/bottomButton/BottomButton.tsx
  src/components/entrance/Entrance.tsx
  src/components/entrance/entranceUtils.ts
  src/components/select/Select.styled.ts
  src/components/spinner/FullSpinner.tsx
  src/components/spinner/Spinner.styled.ts
  src/components/waitingCard/WaitingCard.tsx
  src/components/waitingCard/_hooks/useWaitingCard.tsx
  src/hooks/apis/entry.ts
  src/hooks/apis/waiting.ts
  src/hooks/useCheckWaitingStatus.tsx
  src/hooks/useCountdown.ts
  src/hooks/useIsLoading.ts
  src/layouts/RootLayout.tsx
  src/lib/types/status.ts
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/setting/SettingPage.tsx
  src/pages/setting/_components/deleteID/SettingDeleteID.tsx
  src/pages/signup/SignupPage.tsx
  src/pages/waitingDetail/WaitingDetailPage.tsx
  src/routes/ProtectedRoute.tsx
  src/styles/global.ts
Labels: 🛠️ Fix, 🍀 서현작업

#76 [Fix] #74 - font style, paragraph
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/components/boothCard/boothCardLayout.tsx
  src/constants/waitingCaution.ts
  src/pages/setting/SettingPage.tsx
  src/pages/setting/_components/deleteID/SettingDeleteID.tsx
  src/pages/waitingCheck/WaitingCheckPage.tsx
  src/pages/waitingCheck/_components/WaitingCheckCautionModal.tsx
  src/pages/waitingDetail/_components/WaitingDetailCaution.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: 🛠️ Fix, 🍀 찬주작업

#78 [Fix] #77 - Fixing Entrance Errors
  src/atoms/entrance.ts
  src/hooks/useCountdown.ts
  src/hooks/useEntrance.ts
  src/pages/boothDetail/BoothDetailPage.tsx
Labels: 🛠️ Fix, 🍀 서현작업

#80 [Fix] #77 - Fixing Font System
  src/assets/fonts/Pretendard-Bold.ttf
  src/assets/fonts/Pretendard-Medium.ttf
  src/assets/fonts/Pretendard-SemiBold.ttf
  src/styles/global.ts
  src/styles/theme.ts
Labels: 🛠️ Fix, 🍀 서현작업

#83 [Fix] #81 - Fixing UI
  Todo.json
  src/components/boothCard/BoothCard.styled.ts
  src/layouts/DefaultLayout.tsx
  src/pages/boothDetail/_components/card/BoothDetailCard.tsx
  src/styles/global.ts
Labels: 🛠️ Fix, 🍀 서현작업

#85 [Feature] #84 - Adding Meta Tag
  index.html
  public/images/image_OG_tag.png
  public/images/image_favicon.svg
Labels: ✨ Feature, 🍀 서현작업

#87 [Fix] #86 - Fixing to 3rd QA
  src/apis/domains/waiting/_interfaces.ts
  src/components/entrance/Entrance.tsx
  src/components/waitingCard/WaitingCard.tsx
  src/components/waitingCard/_hooks/useWaitingCard.tsx
  src/hooks/apis/auth.ts
  src/hooks/apis/entry.ts
  src/hooks/apis/waiting.ts
  src/pages/boothDetail/BoothDetailPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/setting/SettingPage.tsx
  src/pages/setting/_components/deleteID/SettingDeleteID.tsx
  src/pages/signup/SignupPage.tsx
  src/pages/waitingCheck/WaitingCheckPage.tsx
  src/pages/waitingCheck/_components/WaitingCheckCautionModal.tsx
  src/pages/waitingCheck/_components/WaitingCheckPeople.styled.ts
  src/pages/waitingDetail/WaitingDetailPage.tsx
Labels: 🛠️ Fix, 🍀 서현작업

#88 [Feature] #88 - Turnstile 적용
  package-lock.json
  package.json
  src/apis/domains/auth/signup/_interfaces.ts
  src/hooks/apis/auth.ts
  src/pages/signup/SignupPage.tsx
Labels: ✨ Feature, :four_leaf_clover: 종범작업

#90 [Fix] #88 - Fix unused import
  src/pages/signup/SignupPage.tsx
Labels: 🛠️ Fix, 🍀 서현작업

#92 [Fix] #91 - Fixing to 4th QA
  src/apis/domains/auth/signup/apis.ts
  src/pages/signup/SignupValidateConfig.ts
  src/pages/waitingCheck/_components/WaitingCheckCautionModal.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: 🛠️ Fix, 🍀 서현작업

#93 [Fix] #91 - Fixing Signup View
  src/pages/signup/SignupPage.tsx
Labels: 🛠️ Fix, 🍀 서현작업
